### PR TITLE
Update ci jobs and dependabot config

### PR DESCRIPTION
**Pull request by cpanato**
To apply some best practices

I have other changes that i will push in different PRs

cc @afrittoli

### CODE REVIEW

**Comment by afrittoli** [comment]
@cpanato would you mind signing the commits?

**Comment by cpanato** [comment]
> @cpanato would you mind signing the commits?

It is signed with gitsign (sigstore)

**Comment by cpanato** [comment]
Unfortunately GitHub does not recognize that as signed yet :(

**Comment by afrittoli** [comment]
Ah, right, I missed that, sorry. Unfortunately, GitHub doesn't let me say I'm happy with the current signature. I think the only option is to disable the requirement for signed commits in the branch protection.

**Pull request merged**
